import React from 'react';
import { 
  Play, 
  BookOpen, 
  Lightbulb, 
  RotateCcw, 
  Code2, 
  Terminal, 
  CheckCircle2,
  AlertCircle,
  Loader2,
  History,
  Trash2,
  UserCircle,
  LogOut,
  X,
  GraduationCap,
  Wand2,
  MessageSquare,
  Github,
  Facebook,
  GitBranch,
  GitCommit,
  GitPullRequest,
  UploadCloud,
  DownloadCloud,
  Clock,
  Image as ImageIcon,
  BrainCircuit,
  Zap,
  Save,
  Check,
  ExternalLink
} from 'lucide-react';

export const Icons = {
  Play,
  BookOpen,
  Lightbulb,
  RotateCcw,
  Code2,
  Terminal,
  Check: CheckCircle2,
  Error: AlertCircle,
  Spinner: Loader2,
  History,
  Trash: Trash2,
  User: UserCircle,
  Logout: LogOut,
  Close: X,
  Learn: GraduationCap,
  Format: Wand2,
  Comment: MessageSquare,
  Github,
  Facebook,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Push: UploadCloud,
  Pull: DownloadCloud,
  Clock,
  Image: ImageIcon,
  Brain: BrainCircuit,
  Fast: Zap,
  Save,
  CheckSimple: Check,
  ExternalLink,
  Wand2
};